config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :people
  resources :states
  mount Ckeditor::Engine => '/ckeditor'
  get 'rooms/index'

  get 'rooms/create'

  get 'rooms/party'

  get 'rooms/config_opentok'

  get 'home/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles
  resources :profiles
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get 'welcome/index'
   resources :welcome do
 member do
      get :following, :followers
    end
collection do
get 'user_list'
end
end
   resources :contacts, only: [:new, :create]

  resources :posts do
   collection { post :import }
    resources :comments
  end
resources :conversations do
member do
post :reply
post :trash
post :untrash
end
end
    resources :rooms
   match '/party/:id' , :to => 'rooms#party', :as => :party, :via => :get

   root 'welcome#index'
get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/chating.rb
class Chating < ActiveRecord::Base
     belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

   scope :involving, -> (user) do
    where("chatings.sender_id =? OR chatings.recipient_id =?",user.id,user.id)
   end

  scope :between, -> (sender_id, recipient_id) do
    where("(chatings.sender_id = ? AND chatings.recipient_id =?) OR (chatings.sender_id = ? AND chatings.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    #attribute :name,      :validate => true
  #attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  #attribute :message
 # attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "nunerajender15@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
    belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

has_many :messages, dependent: :destroy

validates_uniqueness_of :sender_id, :scope => :recipient_id

scope :involving, -> (user) do
where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
end

scope :between, -> (sender_id,recipient_id) do
where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
end
end

app/models/country.rb
class Country < ActiveRecord::Base
     has_many :states
has_many :people
end

app/models/follow.rb
class Follow < ActiveRecord::Base
     belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
end

app/models/person.rb
class Person < ActiveRecord::Base
     belongs_to :country
belongs_to :state
end

app/models/post.rb
class Post < ActiveRecord::Base

    #relationships
        has_many :comments, dependent: :destroy

    #validations
        validates :title, presence: true,
                      length: { minimum:3 }



def self.search(search)
  if search
    Post.where('title LIKE ?', "%#{search}%")
        else
            Post.all
  end
end
def self.import(file)

#sheetsheet = Roo::Spreadsheet.open(file.path)
spreadsheet = open_spreadsheet(file)
header = spreadsheet.row(1)
(2..spreadsheet.last_row).each do |i|
row = Hash[[header, spreadsheet.row(i)].transpose]
post = find_by_id(row["id"]) || new
post.attributes = row.to_hash.slice(*row.to_hash.keys)
p post.attributes
p"==========================="
post.save!
end
end
def self.open_spreadsheet(file)
case File.extname(file.original_filename)
when '.csv' then Roo::CSV.new(file.path, nil, :ignore)
when '.xls' then Roo::Excel.new(file.path)
#Roo::Excelx.new(tempfile.path, )
when '.xlsx' then Roo::Excelx.new(file.path, file_warning: :ignore)
else raise "Unknown file type: #{file.original_filename}"
end
end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
     belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
     belongs_to :country
has_many :people
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,  :omniauthable #, :confirmable

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    #has_attached_file :avatar, :styles => { :medium => "300*300>", :tumb => "100*100#"}
          #has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }

          #---------------------------****  relationships  ***--------#

   has_many :follows
has_many :conversations, :foreign_key => :sender_id
#------------
 has_many :chatings, :foreign_key => :sender_id

    has_many :relationships, foreign_key: "follower_id", dependent: :destroy

  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower







#----------------------------------------
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
#---------------------------------

 acts_as_messageable

def mailboxer_name
self.name
end

def mailboxer_email(object)
self.email
end

def self.from_omniauth(auth)
where(:uid => auth.uid, :provider => auth.provider).first_or_create do |user|
user.provider = auth.provider
user.uid = auth.uid
user.user_name = auth.info.nickname
user.email = auth.info.email
end
end

def password_required?
super && provider.blank?
end

def update_with_password(params, *options)
if encrypted_password.blank?
update_attributes(params, *options)
else
  super
end
end


end

app/controllers/people_controller.rb
class PeopleController < InheritedResources::Base
 def find_state
 states = State.where(country_id: params[:id])
 render :json => [states] if states
 end

  private

    def person_params
      params.require(:person).permit(:name, :country_id, :state_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
     def unread_messages_count
# how to get the number of unread messages for the current user
# using mailboxer
mailbox.inbox(:unread => true).count(:id, :distinct => true)
     end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/people/_form.html.erb
<script>
$(document).ready(function() {

$('#people_country').change(function(){
var id = this.value;
jQuery.get('/peoples/find_state/' + id, function(data){
if(data[0]!= null && data[0]!=""){
$('#people_state').find('option').remove().end()
$('#people_state').append($("<option></option>").attr("value","").text("Select State"));
for (i=0; i <data[0].length; i++ ){
$('#people_state').append($("<option></option>").attr("value",data[0][i].id).text(data[0][i].state_name));
}
}
});
});
});
</script>









<%= simple_form_for(@person) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
<%= f.label :country_id %>
    <%= f.collection_select :country_id, Country.order(:name), :id, :name, include_blank: true %><br />
    <%= f.label :state_id, "State or Province" %>
<%= f.grouped_collection_select :state_id, Country.order(:name), :states, :name, :id, :name, include_blank: true %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1> All My Friends List</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>State</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><p2><%= person.name %></p2></td>
        <td><p1><%= person.country.name %></p1></td>
        <td><%= person.state.name %></td>

        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>
<style>
  p1 {
    color: #339933;
  }
    p2 {
    color: 	#1919FF;
  }

    h1 {
    color: 	#FF704D;
  }
</style>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @person.country_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @person.state_id %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>