config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :people
  resources :states
  mount Ckeditor::Engine => '/ckeditor'
  get 'rooms/index'

  get 'rooms/create'

  get 'rooms/party'

  get 'rooms/config_opentok'

  get 'home/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles
  resources :profiles
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get 'welcome/index'
   resources :welcome do
 member do
      get :following, :followers
    end
collection do
get 'user_list'
end
end
   resources :contacts, only: [:new, :create]

  resources :posts do
   collection { post :import }
    resources :comments
  end
resources :conversations do
member do
post :reply
post :trash
post :untrash
end
end
    resources :rooms
   match '/party/:id' , :to => 'rooms#party', :as => :party, :via => :get

   root 'welcome#index'
get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
    belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

has_many :messages, dependent: :destroy

validates_uniqueness_of :sender_id, :scope => :recipient_id

scope :involving, -> (user) do
where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
end

scope :between, -> (sender_id,recipient_id) do
where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
 before_action :authenticate_user!

def new
end

def create
recipients = User.where(id: conversation_params[:recipients])
conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
flash[:success] = "Your message was successfully sent!"
redirect_to conversation_path(conversation)
end

def show
@receipts = conversation.receipts_for(current_user)
# mark conversation as read
conversation.mark_as_read(current_user)
end

 def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
 end

  def trash
   conversation.move_to_trash(current_user)
   redirect_to mailbox_inbox_path
  end

def untrash
conversation.untrash(current_user)
redirect_to mailbox_inbox_path
end

private

def conversation_params
params.require(:conversation).permit(:subject, :body,recipients:[])
end
 def message_params
    params.require(:message).permit(:body, :subject)
 end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.user_name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.user_name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.user_name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>