config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :people
  resources :states
  mount Ckeditor::Engine => '/ckeditor'
  get 'rooms/index'

  get 'rooms/create'

  get 'rooms/party'

  get 'rooms/config_opentok'

  get 'home/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles
  resources :profiles
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get 'welcome/index'
   resources :welcome do
 member do
      get :following, :followers
    end
collection do
get 'user_list'
end
end
   resources :contacts, only: [:new, :create]

  resources :posts do
   collection { post :import }
    resources :comments
  end
resources :conversations do
member do
post :reply
post :trash
post :untrash
end
end
    resources :rooms
   match '/party/:id' , :to => 'rooms#party', :as => :party, :via => :get

   root 'welcome#index'
get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,  :omniauthable #, :confirmable

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    #has_attached_file :avatar, :styles => { :medium => "300*300>", :tumb => "100*100#"}
          #has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }

          #---------------------------****  relationships  ***--------#

   has_many :follows
has_many :conversations, :foreign_key => :sender_id
#------------
 has_many :chatings, :foreign_key => :sender_id

    has_many :relationships, foreign_key: "follower_id", dependent: :destroy

  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower







#----------------------------------------
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
#---------------------------------

 acts_as_messageable

def mailboxer_name
self.name
end

def mailboxer_email(object)
self.email
end

def self.from_omniauth(auth)
where(:uid => auth.uid, :provider => auth.provider).first_or_create do |user|
user.provider = auth.provider
user.uid = auth.uid
user.user_name = auth.info.nickname
user.email = auth.info.email
end
end

def password_required?
super && provider.blank?
end

def update_with_password(params, *options)
if encrypted_password.blank?
update_attributes(params, *options)
else
  super
end
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,
                only: [:index, :edit, :update, :destroy, :following, :followers]


  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :email %>
  <%= error_span(@user[:email]) %>
  <%= f.input :encrypted_password %>
  <%= error_span(@user[:encrypted_password]) %>
  <%= f.input :reset_password_token %>
  <%= error_span(@user[:reset_password_token]) %>
  <%= f.input :reset_password_sent_at %>
  <%= error_span(@user[:reset_password_sent_at]) %>
  <%= f.input :remember_created_at %>
  <%= error_span(@user[:remember_created_at]) %>
  <%= f.input :current_sign_in_at %>
  <%= error_span(@user[:current_sign_in_at]) %>
  <%= f.input :last_sign_in_at %>
  <%= error_span(@user[:last_sign_in_at]) %>
  <%= f.input :current_sign_in_ip %>
  <%= error_span(@user[:current_sign_in_ip]) %>
  <%= f.input :last_sign_in_ip %>
  <%= error_span(@user[:last_sign_in_ip]) %>
  <%= f.input :confirmation_token %>
  <%= error_span(@user[:confirmation_token]) %>
  <%= f.input :confirmed_at %>
  <%= error_span(@user[:confirmed_at]) %>
  <%= f.input :confirmation_sent_at %>
  <%= error_span(@user[:confirmation_sent_at]) %>
  <%= f.input :unconfirmed_email %>
  <%= error_span(@user[:unconfirmed_email]) %>
  <%= f.input :avatar_file_name %>
  <%= error_span(@user[:avatar_file_name]) %>
  <%= f.input :avatar_content_type %>
  <%= error_span(@user[:avatar_content_type]) %>
  <%= f.input :avatar_file_size %>
  <%= error_span(@user[:avatar_file_size]) %>
  <%= f.input :avatar_updated_at %>
  <%= error_span(@user[:avatar_updated_at]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:confirmation_token) %></th>
      <th><%= model_class.human_attribute_name(:confirmed_at) %></th>
      <th><%= model_class.human_attribute_name(:confirmation_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:unconfirmed_email) %></th>
      <th><%= model_class.human_attribute_name(:avatar_file_name) %></th>
      <th><%= model_class.human_attribute_name(:avatar_content_type) %></th>
      <th><%= model_class.human_attribute_name(:avatar_file_size) %></th>
      <th><%= model_class.human_attribute_name(:avatar_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= user.confirmation_token %></td>
        <td><%= user.confirmed_at %></td>
        <td><%= user.confirmation_sent_at %></td>
        <td><%= user.unconfirmed_email %></td>
        <td><%= user.avatar_file_name %></td>
        <td><%= user.avatar_content_type %></td>
        <td><%= user.avatar_file_size %></td>
        <td><%= user.avatar_updated_at %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:confirmation_token) %>:</strong></dt>
  <dd><%= @user.confirmation_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:confirmed_at) %>:</strong></dt>
  <dd><%= @user.confirmed_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:confirmation_sent_at) %>:</strong></dt>
  <dd><%= @user.confirmation_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unconfirmed_email) %>:</strong></dt>
  <dd><%= @user.unconfirmed_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_name) %>:</strong></dt>
  <dd><%= @user.avatar_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_content_type) %>:</strong></dt>
  <dd><%= @user.avatar_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_size) %>:</strong></dt>
  <dd><%= @user.avatar_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_updated_at) %>:</strong></dt>
  <dd><%= @user.avatar_updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>