config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :people
  resources :states
  mount Ckeditor::Engine => '/ckeditor'
  get 'rooms/index'

  get 'rooms/create'

  get 'rooms/party'

  get 'rooms/config_opentok'

  get 'home/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles
  resources :profiles
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get 'welcome/index'
   resources :welcome do
 member do
      get :following, :followers
    end
collection do
get 'user_list'
end
end
   resources :contacts, only: [:new, :create]

  resources :posts do
   collection { post :import }
    resources :comments
  end
resources :conversations do
member do
post :reply
post :trash
post :untrash
end
end
    resources :rooms
   match '/party/:id' , :to => 'rooms#party', :as => :party, :via => :get

   root 'welcome#index'
get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/models/post.rb
class Post < ActiveRecord::Base

    #relationships
        has_many :comments, dependent: :destroy

    #validations
        validates :title, presence: true,
                      length: { minimum:3 }



def self.search(search)
  if search
    Post.where('title LIKE ?', "%#{search}%")
        else
            Post.all
  end
end
def self.import(file)

#sheetsheet = Roo::Spreadsheet.open(file.path)
spreadsheet = open_spreadsheet(file)
header = spreadsheet.row(1)
(2..spreadsheet.last_row).each do |i|
row = Hash[[header, spreadsheet.row(i)].transpose]
post = find_by_id(row["id"]) || new
post.attributes = row.to_hash.slice(*row.to_hash.keys)
p post.attributes
p"==========================="
post.save!
end
end
def self.open_spreadsheet(file)
case File.extname(file.original_filename)
when '.csv' then Roo::CSV.new(file.path, nil, :ignore)
when '.xls' then Roo::Excel.new(file.path)
#Roo::Excelx.new(tempfile.path, )
when '.xlsx' then Roo::Excelx.new(file.path, file_warning: :ignore)
else raise "Unknown file type: #{file.original_filename}"
end
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
require "prawn"
 #before_filter :authenticate_user!, :except => [:show, :index]
 before_filter :authenticate_user!, :except => [:show, :index]



    def index
# @post = Post.all
        @post = Post.search(params[:search]).paginate(:page => params[:page], :per_page => 3)

#format.pdf do
      #send_data PostDrawer.draw(@posts), :filename => 'posts.pdf', :type => 'application/pdf', :disposition => 'inline'
    #end

    end

    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end
    def edit
        @post = Post.find(params[:id])
    end

    def create

        #@post = Post.new(params[:post])
        #@post = Post.new(params.require(:post).permit(:title, :text))

        @post = Post.new(post_params) #adding strong parameters method name here
        #@comment = @post.comments.create(comment_params)
        @post.user_id = current_user.id

        if @post.save
            ExampleMailer.sample_email(@post).deliver_now
        redirect_to @post
        else
            render 'new'
        end
    end
        #render plain: params[:post].inspect
        #render plain: params[:post].inspect

    def update

        @post =Post.find(params[:id])
        if @post.update(post_params)
        redirect_to @post
        else
             render 'edit'
        end
    end

            # in RESTful CRUD its D

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to @post
    end
  def download_pdf
    post = Post.find(params[:id])
    send_data generate_pdf(post),
              filename: "#{post.title}.pdf",
              type: "application/pdf"
  end

  def import
    if (params[:file])

    Post.import(params[:file])
    redirect_to root_url, notice: "Posts imported."
    else
    redirect_to posts_path, notice: " No file selected."
    end
  end



    private

  def generate_pdf(post)
    Prawn::Document.new do
      text post.title, align: :center
      text "Text: #{post.text}"

    end.render
  end

    def post_params
        params.require(:post).permit(:title, :text)  # this is for  strong parameters
    end

    #def comment_params
       # params.require(:comment).permit(:commenter, :body)
    #end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<div id="error_explanation">
<h2> <%= pluralize(@post.errors.count, "error") %> prohibited
this post from being savad:????
</h2>
<ul>
<% @post.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
    <% end %>
    </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %> <br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>
    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
 <%= form_tag(posts_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Posts" %>
      <!-- In post to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
      <button class="btn btn-info" type="submit"><i class="icon-search"></i>submit</button>
    </div>
  <% end %>




<br>
<h2>Import post</h2>

<%= form_tag import_posts_path, multipart: true do %>
<%= file_field_tag :file %></br>
<%= submit_tag "Import"  %>
<% end %>


<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>


<table class="table table-striped">


  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @post.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%=l post.created_at %></td>

        <td>
<%= link_to t('.show', :default => t("helpers.links.show")), post, :onclick=>"window.open(this.href,'show_post','height=600, width=600');return false;"%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="pager">
           <!------------------------------------>
          <%= will_paginate @post, renderer: BootstrapPagination::Rails %>


</div>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%= link_to 'Back', posts_path %>
<p>
    <strong> Title: </strong>
    <%= @post.title %>
    </p>
    <p>
        <strong> Text: </strong>
        <%= @post.text %>
        </p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_post_path(@post) %>